# Generated by Django 2.2.9 on 2019-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_musical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='latitud',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='longitud',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
