# docker-compose.yml

version: '3.7'

services:
  ejercicios:
    image: python:3.7
    volumes:
      - ./ejer:/ejer
    working_dir: /ejer

  flask:
    build:
      context: .
      dockerfile: flask_dockerfile
    ports:
      - "8080:5000"
    volumes:
      - ./flask:/flask
    working_dir: /flask

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump              # los datos de prueba
      - ./datos_db:/data/db       # almacenamiento en el host
